const categories = ['Light', 'Dark', 'Neon', 'Minimal', 'Flat'];

const themes = [
  {
    name: 'theme-light',
    title: 'Default',
    category: 'light',
    primarycolor: '#1DA1F2',
    backgroundcolor: '#f1f1f1',
    hovercolor: '#f7f7f7',
    cardbackground: '#ffffff',
    accentcolor: '#f1f1f1',
    textcolor: '#222222',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-light-red',
    title: 'Red',
    category: 'light',
    primarycolor: '#ff3211',
    backgroundcolor: '#f1f1f1',
    hovercolor: '#f7f7f7',
    cardbackground: '#ffffff',
    accentcolor: '#f1f1f1',
    textcolor: '#222222',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-light-pink',
    title: 'Pink',
    category: 'light',
    primarycolor: '#f711a6',
    backgroundcolor: '#f1f1f1',
    hovercolor: '#f7f7f7',
    cardbackground: '#ffffff',
    accentcolor: '#f1f1f1',
    textcolor: '#222222',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-light-purple',
    title: 'Purple',
    category: 'light',
    primarycolor: '#7d24f3',
    backgroundcolor: '#f1f1f1',
    hovercolor: '#f7f7f7',
    cardbackground: '#ffffff',
    accentcolor: '#f1f1f1',
    textcolor: '#222222',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-light-green',
    title: 'Green',
    category: 'light',
    primarycolor: '#00dc52',
    backgroundcolor: '#f1f1f1',
    hovercolor: '#f7f7f7',
    cardbackground: '#ffffff',
    accentcolor: '#f1f1f1',
    textcolor: '#222222',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-dark',
    title: 'Default',
    category: 'dark',
    primarycolor: '#1DA1F2',
    backgroundcolor: '#000000',
    hovercolor: '#ffffff10',
    cardbackground: '#232323',
    accentcolor: '#ffffff20',
    textcolor: '#fbfbfb',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-dark-white',
    title: 'White',
    category: 'dark',
    primarycolor: '#ffffff',
    backgroundcolor: '#000000',
    hovercolor: '#ffffff10',
    cardbackground: '#232323',
    accentcolor: '#ffffff20',
    textcolor: '#fbfbfb',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#000000',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-dark-red',
    title: 'Red',
    category: 'dark',
    primarycolor: '#ff3211',
    backgroundcolor: '#000000',
    hovercolor: '#ffffff10',
    cardbackground: '#232323',
    accentcolor: '#ffffff20',
    textcolor: '#fbfbfb',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-dark-pink',
    title: 'Pink',
    category: 'dark',
    primarycolor: '#f711a6',
    backgroundcolor: '#000000',
    hovercolor: '#ffffff10',
    cardbackground: '#232323',
    accentcolor: '#ffffff20',
    textcolor: '#fbfbfb',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-dark-purple',
    title: 'Purple',
    category: 'dark',
    primarycolor: '#7d24f3',
    backgroundcolor: '#000000',
    hovercolor: '#ffffff10',
    cardbackground: '#232323',
    accentcolor: '#ffffff20',
    textcolor: '#fbfbfb',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-dark-green',
    title: 'Green',
    category: 'dark',
    primarycolor: '#00dc52',
    backgroundcolor: '#000000',
    hovercolor: '#ffffff10',
    cardbackground: '#232323',
    accentcolor: '#ffffff20',
    textcolor: '#fbfbfb',
    radius: '6px',
    cardshadow:
      'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
    buttonradius: '6px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-minimal',
    title: 'Default',
    category: 'minimal',
    primarycolor: '#000000',
    backgroundcolor: '#f7f7f7',
    hovercolor: '#00000008',
    cardbackground: '#ffffff',
    accentcolor: '#e8e8e8',
    textcolor: '#111111',
    radius: '2px',
    cardshadow: 'none',
    buttonradius: '2px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-minimal-red',
    title: 'Red',
    category: 'minimal',
    primarycolor: '#ff3211',
    backgroundcolor: '#f7f7f7',
    hovercolor: '#ff321108',
    cardbackground: '#ffffff',
    accentcolor: '#e8e8e8',
    textcolor: '#111111',
    radius: '2px',
    cardshadow: 'none',
    buttonradius: '2px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-minimal-pink',
    title: 'Pink',
    category: 'minimal',
    primarycolor: '#f711a6',
    backgroundcolor: '#f7f7f7',
    hovercolor: '#f711a608',
    cardbackground: '#ffffff',
    accentcolor: '#e8e8e8',
    textcolor: '#111111',
    radius: '2px',
    cardshadow: 'none',
    buttonradius: '2px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-minimal-purple',
    title: 'Purple',
    category: 'minimal',
    primarycolor: '#7d24f3',
    backgroundcolor: '#f7f7f7',
    hovercolor: '#7d24f308',
    cardbackground: '#ffffff',
    accentcolor: '#e8e8e8',
    textcolor: '#111111',
    radius: '2px',
    cardshadow: 'none',
    buttonradius: '2px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-minimal-green',
    title: 'Green',
    category: 'minimal',
    primarycolor: '#00dc52',
    backgroundcolor: '#f7f7f7',
    hovercolor: '#00dc5208',
    cardbackground: '#ffffff',
    accentcolor: '#e8e8e8',
    textcolor: '#111111',
    radius: '2px',
    cardshadow: 'none',
    buttonradius: '2px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-neon',
    title: 'Default',
    category: 'neon',
    primarycolor: '#1da1f2',
    backgroundcolor: '#000000',
    hovercolor: '#1da1f210',
    accentcolor: '#121212',
    textcolor: '#ffffff',
    cardbackground: '#000000',
    radius: '6px',
    cardshadow:
      '0px 0px 0px 1px #1da1f290, 0 0 0 4px #1da1f230, 0px 0px 0px 8px #1da1f212',
    buttontextcolor: '#ffffff',
    buttonradius: '6px',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-neon-red',
    title: 'Red',
    category: 'neon',
    primarycolor: '#ff3211',
    backgroundcolor: '#000000',
    hovercolor: '#ff321110',
    accentcolor: '#121212',
    textcolor: '#ffffff',
    cardbackground: '#000000',
    radius: '6px',
    cardshadow:
      '0px 0px 0px 1px #ff321190, 0 0 0 4px #ff321130, 0px 0px 0px 8px #ff321112',
    buttontextcolor: '#ffffff',
    buttonradius: '6px',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-neon-pink',
    title: 'Pink',
    category: 'neon',
    primarycolor: '#f711a6',
    backgroundcolor: '#000000',
    hovercolor: '#f711a610',
    accentcolor: '#121212',
    textcolor: '#ffffff',
    cardbackground: '#000000',
    radius: '6px',
    cardshadow:
      '0px 0px 0px 1px #f711a690, 0 0 0 4px #f711a630, 0px 0px 0px 8px #f711a612',
    buttontextcolor: '#ffffff',
    buttonradius: '6px',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-neon-purple',
    title: 'Purple',
    category: 'neon',
    primarycolor: '#7d24f3',
    backgroundcolor: '#000000',
    hovercolor: '#7d24f310',
    accentcolor: '#121212',
    textcolor: '#ffffff',
    cardbackground: '#000000',
    radius: '6px',
    cardshadow:
      '0px 0px 0px 1px #7d24f390, 0 0 0 4px #7d24f330, 0px 0px 0px 8px #7d24f312',
    buttontextcolor: '#ffffff',
    buttonradius: '6px',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-neon-green',
    title: 'Green',
    category: 'neon',
    primarycolor: '#00dc52',
    backgroundcolor: '#000000',
    hovercolor: '#00dc5210',
    accentcolor: '#121212',
    textcolor: '#ffffff',
    cardbackground: '#000000',
    radius: '6px',
    cardshadow:
      '0px 0px 0px 1px #00dc5290, 0 0 0 4px #00dc5230, 0px 0px 0px 8px #00dc5212',
    buttontextcolor: '#ffffff',
    buttonradius: '6px',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },












    {
    name: 'theme-flat',
    title: 'Default',
    category: 'flat',
    primarycolor: '#1DA1F2',
    backgroundcolor: '#ffffff',
    hovercolor: '#e8e8e8',
    cardbackground: '#f7f7f7',
    accentcolor: '#dddddd',
    textcolor: '#222222',
    radius: '3px',
    cardshadow:
      '0 0 0 1px #dddddd',
    buttonradius: '3px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-flat-red',
    title: 'Red',
    category: 'flat',
    primarycolor: '#ff3211',
    backgroundcolor: '#ffffff',
    hovercolor: '#e8e8e8',
    cardbackground: '#f7f7f7',
    accentcolor: '#dddddd',
    textcolor: '#222222',
    radius: '3px',
    cardshadow:
      '0 0 0 1px #dddddd',
    buttonradius: '3px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-flat-pink',
    title: 'Pink',
    category: 'flat',
    primarycolor: '#f711a6',
    backgroundcolor: '#ffffff',
    hovercolor: '#e8e8e8',
    cardbackground: '#f7f7f7',
    accentcolor: '#dddddd',
    textcolor: '#222222',
    radius: '3px',
    cardshadow:
      '0 0 0 1px #dddddd',
    buttonradius: '3px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-flat-purple',
    title: 'Purple',
    category: 'flat',
    primarycolor: '#7d24f3',
    backgroundcolor: '#ffffff',
    hovercolor: '#e8e8e8',
    cardbackground: '#f7f7f7',
    accentcolor: '#dddddd',
    textcolor: '#222222',
    radius: '3px',
    cardshadow:
      '0 0 0 1px #dddddd',
    buttonradius: '3px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
  {
    name: 'theme-flat-green',
    title: 'Green',
    category: 'flat',
    primarycolor: '#00dc52',
    backgroundcolor: '#ffffff',
    hovercolor: '#e8e8e8',
    cardbackground: '#f7f7f7',
    accentcolor: '#dddddd',
    textcolor: '#222222',
    radius: '3px',
    cardshadow:
      '0 0 0 1px #dddddd',
    buttonradius: '3px',
    buttontextcolor: '#ffffff',
    inputtextcolor: '#111111',
    inputbackground: '#ffffff',
  },
];

// const solarizedTheme = {
//   primarycolor: '#1DA1F2',
//   backgroundcolor: '#1a1e21',
//   hovercolor: '#273036',
//   cardbackground: '#2c363c',
//   accentcolor: '#565f65',
//   textcolor: '#fcfcfc',
//   radius: '6px',
//   cardshadow:
//     'rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px',
//   buttonbackground: '#1DA1F2',
//   buttonradius: '6px',
//   buttontextcolor: '#ffffff',
//   inputtextcolor: '#111111',
//   inputbackground: '#ffffff',
// };
// const flatTheme = {
//   primarycolor: '#1da1f2',
//   backgroundcolor: '#ffffff',
//   hovercolor: '#e8e8e8',
//   accentcolor: '#e8e8e8',
//   textcolor: '#333333',
//   cardbackground: '#f7f7f7',
//   radius: '2px',
//   cardshadow: '0px 0px 0px 1px #d8d8d8',
//   buttonbackground: '#1da1f2',
//   buttontextcolor: '#ffffff',
//   buttonradius: '2px',
//   inputtextcolor: '#111111',
//   inputbackground: '#ffffff',
// };

// const flatGreenTheme = {
//   primarycolor: '#36a927',
//   backgroundcolor: '#ffffff',
//   hovercolor: '#e8e8e8',
//   accentcolor: '#e8e8e8',
//   textcolor: '#333333',
//   cardbackground: '#f7f7f7',
//   radius: '2px',
//   cardshadow: '0px 0px 0px 1px #d8d8d8',
//   buttonbackground: '#36a927',
//   buttontextcolor: '#ffffff',
//   buttonradius: '2px',
//   inputtextcolor: '#111111',
//   inputbackground: '#ffffff',
// };

// const flatRedTheme = {
//   primarycolor: '#d64343',
//   backgroundcolor: '#ffffff',
//   hovercolor: '#e8e8e8',
//   accentcolor: '#e8e8e8',
//   textcolor: '#333333',
//   cardbackground: '#f7f7f7',
//   radius: '2px',
//   cardshadow: '0px 0px 0px 1px #d8d8d8',
//   buttonbackground: '#d64343',
//   buttontextcolor: '#ffffff',
//   buttonradius: '2px',
//   inputtextcolor: '#111111',
//   inputbackground: '#ffffff',
// };

// const flatPinkTheme = {
//   primarycolor: '#c34fc0',
//   backgroundcolor: '#ffffff',
//   hovercolor: '#e8e8e8',
//   accentcolor: '#e8e8e8',
//   textcolor: '#333333',
//   cardbackground: '#f7f7f7',
//   radius: '2px',
//   cardshadow: '0px 0px 0px 1px #d8d8d8',
//   buttonbackground: '#c34fc0',
//   buttontextcolor: '#ffffff',
//   buttonradius: '2px',
//   inputtextcolor: '#111111',
//   inputbackground: '#ffffff',
// };
